---
- name: apt update
  apt:
    update: yes

- name: apt install openjdk-8
  apt:
    name: openjdk-8-jdk

- name: wget to add key repository
  shell: wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -

- name: Download repository
  shell: sudo sh -c 'echo deb https://pkg.jenkins.io/debian-stable binary/ > \
    /etc/apt/sources.list.d/jenkins.list'

- name: apt update
  apt:
    update: yes

- name: apt install jenkins
  apt:
    name: jenkins