---
- name: apt update
  apt:
    update: yes

- name: install apt-transport-https
  apt:
    name: apt-transport-https
    
- name: install ca-certificates
  apt:
    name: ca-certificates

- name: install curl
  apt:
    name: curl

- name: install gnupg-agent
  apt:
    name: gnupg-agent

- name: install software-properties-common
  apt:
    name: software-properties-common

- name: Add Docker’s official GPG key
  shell: 'curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -'

- name: Verify fingerprint
  shell: 'apt-key fingerprint 0EBFCD88'
  remote_user: root

- name: Add repository
  shell: 'add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"'
  remote_user: root

- name: apt update
  apt:
    update: yes

- name: apt install docker-ce
  apt:
    name: docker-ce
  remote_user: root
- name: apt install docker-ce-cli
  apt:
    name: docker-ce-cli
  remote_user: root

- name: apt install containerd.io
  apt:
    name: containerd.io
  remote_user: root